# Generated by Django 4.1.7 on 2023-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_scheduledemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
    ]
