# Generated by Django 4.1.7 on 2023-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_scheduledemail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='campaign_name',
            field=models.CharField(default='unique value', max_length=200),
        ),
    ]
