# Generated by Django 4.1.7 on 2023-07-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_scheduledemail_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='attach_file',
            field=models.FileField(blank='true', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='csv_file',
            field=models.FileField(blank='true', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
    ]
